<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title><?php echo A('title', 'My website') ?></title>
		
		<?php foreach (A('styles', array()) as $style): ?>
		<link rel="stylesheet" type="text/css" href="<?php echo Atomik::appAsset($style) ?>" />
		<?php endforeach; ?>
		
		<?php foreach (A('scripts', array()) as $script): ?>
		<script type="text/javascript" src="<?php echo Atomik::appAsset($script) ?>"></script>
		<?php endforeach; ?>
	</head>
	<body>
		<ul id="messages">
			<?php foreach (A('flash:all') as $label => $messages): ?>
				<?php foreach ($messages as $message): ?>
					<li class="<?php echo $label ?>"><?php echo $message ?></li>
				<?php endforeach; ?>
			<?php endforeach; ?>
		</ul>
	
		<div id="content">
			<?php echo $contentForLayout; ?>
		</div>
	</body>
</html>
