<div id="atomik-wrapper">
	<div id="atomik">
		<h1>Congratulations, you're ready to roll!</h1>
		<p>
			If this page is showing, it means the application has been successfully created.
		</p>
		<p>
			This is the default page of your website. You can edit it in <em>app/views/index.phtml</em>.
		</p>
		<h3>What's next?</h3>
		<ol>
			<li>Add some plugins</li>
			<li>Configure your bootstrap file</li>
		</ol>
	</div>
	<a href="http://www.atomikframework.com">
		<img src="<?php echo Atomik::asset('assets/images/atomik-powered.png') ?>" alt="Powered by Atomik Framework" />
	</a>
</div>