<div id="content-wrapper">
	<div class="panel">
		<h2 class="panel-title"><?php echo __('Models') ?></h2>
		<div class="panel-content" id="content">
			<?php echo $this->dataTable('models', $models, array(
						'columns' => array('name'),
						'id_column' => 'name',
						'url' => Atomik::pluginUrl('list'),
						'url_param' => 'name'
			)) ?>
		</div>
	</div>
</div>
<div id="sidebar-wrapper">
	<div id="sidebar">
	</div>
</div>
