<div id="content-wrapper">
	<div class="panel">
		<h2 class="panel-title"><?php echo $modelName ?></h2>
		<div class="panel-content" id="content">
			<?php echo $this->dataTable($modelName, $models, array(
						'url' => Atomik::pluginUrl('edit', array('name' => $modelName)),
						'columns' => $columns,
						'actions' => array(
							array('label' => __('Delete'), 'url' => Atomik::pluginUrl('delete', array('name' => $modelName)))
						)
			)) ?>
		</div>
	</div>
</div>
<div id="sidebar-wrapper">
	<div id="sidebar">
		<?php echo $this->sidebarButton(__('Create a new %s', $modelName), Atomik::pluginUrl('edit', array('name' => $modelName))) ?>
	</div>
</div>
