<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title><?php echo $this->get('title', 'My website') ?></title>
		
		<?php foreach ($this->get('styles', array()) as $style): ?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->asset("assets/css/$style") ?>" />
		<?php endforeach; ?>
		
		<?php foreach ($this->get('scripts', array()) as $script): ?>
		<script type="text/javascript" src="<?php echo $this->asset("assets/js/$script") ?>"></script>
		<?php endforeach; ?>
	</head>
	<body>
		<ul id="messages">
			<?php foreach ($this['flash:all'] as $label => $messages): ?>
				<?php foreach ($messages as $message): ?>
					<li class="<?php echo $label ?>"><?php echo $this->escape($message) ?></li>
				<?php endforeach; ?>
			<?php endforeach; ?>
		</ul>
	
		<div id="content">
			<?php echo $contentForLayout; ?>
		</div>
	</body>
</html>
