<?php Atomik::add('backend/styles', 'css/activities.css') ?>

<div id="content-wrapper">
	<div class="panel">
		<h2 class="panel-title"><?php echo __('Latest updates') ?></h2>
		<div class="panel-content" id="content">
			<ul id="activities">
				<?php foreach ($activities as $activity): ?>
					<li class="activity">
						<span class="label"><?php echo $activity->label ?></span>
						<span class="message"><?php echo $activity->message ?></span>
						<span class="userAction"><?php echo $activity->userAction ?></span>
						<div class="clear"></div>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
</div>
<div id="sidebar-wrapper">
	<div id="sidebar">
		
	</div>
</div>