<?php Atomik_Backend_Assets::addStyle('css/activities.css') ?>

<div id="content-wrapper">
	<div class="panel">
		<h2 class="panel-title"><?php echo __('Latest updates') ?></h2>
		<div class="panel-content" id="content">
			<ul id="activities">
				<?php foreach ($activities as $activity): ?>
					<li class="activity">
						<span class="label"><?php echo $activity->label ?></span>
						<span class="message"><?php echo $activity->message ?></span>
						<span class="userAction">
							<?php echo $activity->userAction ?> the 
							<?php echo $this->sqlDate($activity->created, 'jS \o\f M') ?>
						</span>
						<div class="clear"></div>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
</div>
<div id="sidebar-wrapper">
	<div id="sidebar">
		<p>
			<?php echo __('The backend allows you to easily manage your application.') ?>
		</p>
		<p>
			<?php echo __('Plugins can provide their own administration pages. Check the plugin\'s documentation to know if it supports the backend.') ?>
		</p>
	</div>
</div>