<div id="content-wrapper">
	<div class="panel">
		<h2 class="panel-title"><?php echo __('Pages') ?></h2>
		<div class="panel-content" id="content">
			<p>
				<strong><?php echo __('It seems that none of your pages are editable') ?>.</strong>
			</p>
			<p>
				<?php echo __('Have a look at the documentation to discover how ' .
								'to make your pages editable from the backend'); ?>.
			</p>
		</div>
	</div>
</div>
<div id="sidebar-wrapper">
	<div id="sidebar">
		<p><?php echo __('Pages are views that you made editable through the backend') ?>.</p>
		<p><?php echo __('Simply add the atomik class to any of your HTML elements') ?>.</p>
	</div>
</div>
