<div id="content-wrapper">
	<div class="panel">
		<h2 class="panel-title"><?php echo __('Users') ?></h2>
		<div class="panel-content" id="content">
			<?php echo $this->modelDataTable('users', $users, array(
						'url' => Atomik_Backend::pluginUrl('db', 'models/edit', 
							array('name' => 'User', 'returnUrl' => Atomik::url('index'))),
						'columns' => $columns,
						'actions' => array(
							array('label' => __('Delete'), 'url' => Atomik_Backend::pluginUrl('db', 'models/delete', 
								array('name' => 'User', 'returnUrl' => Atomik::url('index'))))
						)
			))->render() ?>
		</div>
	</div>
</div>
<div id="sidebar-wrapper">
	<div id="sidebar">
		<?php echo $this->sidebarButton(
			__('Create a new user'), 
			Atomik_Backend::pluginUrl('db', 'models/edit', array('name' => 'User', 'returnUrl' => Atomik::url('index'))),
			Atomik::asset('images/user.png')
		) ?>
		<?php echo $this->sidebarButton(
			__('Manage permissions'), 
			Atomik::url('permissions'),
			Atomik::asset('images/permission.png')
		) ?>
		<?php echo $this->modelFilters($builder) ?>
	</div>
</div>