<div id="content-wrapper">
	<div class="panel">
		<h2 class="panel-title"><?php echo __('Users') ?></h2>
		<div class="panel-content" id="content">
			<?php echo __('User management is only supported when the Model adapter is used.') ?>
		</div>
	</div>
</div>
<div id="sidebar-wrapper">
	<div id="sidebar">
		<?php echo $this->sidebarButton(
			__('Manage permissions'), 
			Atomik::url('permissions'),
			Atomik::pluginAsset('images/permission.png')
		) ?>
	</div>
</div>