<div id="content-wrapper">
	<div class="panel">
		<h2 class="panel-title"><?php echo __('Permissions') ?></h2>
		<div class="panel-content" id="content">
			<?php echo $this->dataTable('permissions', $permissions, array(
						'url' => Atomik::url('permissions/edit'),
						'idColumn' => 'uri',
						'actions' => array(
							array('label' => __('Delete'), 'url' => Atomik::url('permissions/delete'))
						)
			)) ?>
		</div>
	</div>
</div>
<div id="sidebar-wrapper">
	<div id="sidebar">
		<?php echo $this->sidebarButton(
			__('Create a new permission'), 
			Atomik::url('permissions/edit'),
			Atomik::pluginAsset('images/permission.png')
		) ?>
	</div>
</div>