<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>
			<?php 
				$currentMenuItem = Atomik_Backend::getCurrentMenu();
				echo __($currentMenuItem['label']) . ' | '. Atomik::get('backend/title'); 
			?>
		</title>
		
		<?php echo Atomik_Assets::render() ?>
		<?php echo Atomik_Backend_Layout::renderPlaceholder('head') ?>
	</head>
	<body>
		<div id="body">
			<div id="header">
				<div id="header-info">
					Logged in as <?php echo Atomik_Auth::getCurrentUsername() ?> | 
					<a href="<?php echo Atomik::pluginUrl('Auth', 'logout') ?>">Log out</a> | 
					<a href="<?php echo Atomik::appUrl('/') ?>">View site</a>
				</div>
				<h1><?php echo Atomik::get('backend/title'); ?></h1>
				
				<ul id="menu">
					<?php echo Atomik_Backend_Layout::renderPlaceholder('before_menu') ?>
					
					<?php foreach (Atomik_Backend::getMenu() as $name => $item): ?>
						<li class="<?php if ($name == $currentMenuItem['name']) echo 'selected '; echo $item['position']; ?>">
							<a href="<?php echo Atomik::pluginUrl('Backend', $item['action']) ?>">
								<?php echo __(ucfirst($item['label'])); ?>
							</a>
						</li>
					<?php endforeach; ?>
					
					<?php echo Atomik_Backend_Layout::renderPlaceholder('after_menu') ?>
				</ul>
				<ul id="sub-menu">
					<?php echo Atomik_Backend_Layout::renderPlaceholder('before_submenu') ?>
					
					<?php foreach ($currentMenuItem['submenu'] as $label => $action): ?>
						<li><a href="<?php echo Atomik::pluginUrl('Backend', $action) ?>">
							<?php echo __($label) ?>
						</a></li>
					<?php endforeach; ?>
					
					<?php echo Atomik_Backend_Layout::renderPlaceholder('before_submenu') ?>
				</ul>
			</div>
			
			<div id="main">
				<div id="messages">
					<?php foreach (Atomik::get('flash:all') as $label => $messages): ?>
						<?php foreach ($messages as $message): ?>
							<div class="message <?php echo $label ?>">
								<?php echo $message ?>
							</div>
						<?php endforeach; ?>
					<?php endforeach; ?>
					
					<?php echo Atomik_Backend_Layout::renderPlaceholder('messages') ?>
				</div>
				
				<?php echo Atomik_Backend_Layout::renderPlaceholder('before_content') ?>
				<?php echo $contentForLayout ?>
				<?php echo Atomik_Backend_Layout::renderPlaceholder('after_content') ?>
				
				<div class="clear"></div>
			</div>
			
			<div id="footer">
				<?php echo Atomik_Backend_Layout::renderPlaceholder('footer') ?>
				Thank you for using Atomik Framework. <a href="http://www.atomikframework.com">www.atomikframework.com</a>
			</div>
		</div>
	</body>
</html>
